### ISSUE TITLE
Manual OpenAI async code vs official AsyncOpenAI

### ISSUE THREAD

**Issue by chemeris** [HumanSignal/Adala#100]
I noticed that you're making async calls to OpenAI API manually in `async def async_create_completion()`. Is there any reason for this instead of using the `AsyncOpenAI` from the official library?

The reason I found this is because I was instrumenting our app with [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-python) and [OpenLLMetry](https://github.com/traceloop/openllmetry/) just to find that async OpenAI calls from Adala are not instrumented - because OpenLLMetry expects standard `openai` package calls. It would be great to stick to the official package to make this (and other) useful tricks working.

**Comment by chemeris** [comment]
Hi, still looking for a response

**Comment by matt-bernstein** [comment]
Hi, thanks for reaching out! Happy to say this is under development in #120 and should be merged in next week. Interested to hear more about your use case if you have details to share.

**Comment by chemeris** [comment]
Thank you. This is great to hear!
I hope it'll make it easier for us to use LangFuse or something similar as we move towards more instrumentation and observability for our production environment.

PS I'm happy to share our use cases privately, as we're working on an internal proprietary tool.
I would also appreciate it if our (very simple) bugfixes are merged (or fixed otherwise) - like this one: https://github.com/HumanSignal/Adala/pull/98

**Comment by chemeris** [comment]
Fixed in #120
