### ISSUE TITLE
Generalize LLM Params for OpenAI

### ISSUE THREAD

**Issue by tambulkar** [HumanSignal/Adala#33]
I think we should be able to pass in more params when initializing an openAI LLM. For example I want to change the endpoint to point to an internal openai instance but would need to write a basically identical OpenAI Runtime class with a minor change. If we could just pass through kwargs to the guidance LLM so we support [all their args](https://guidance.readthedocs.io/en/latest/generated/guidance.llms.OpenAI.html) that would be great. Id be happy to add the PR as well.

**Comment by makseq** [comment]
Hello, great idea! Are you able to contribute it?

**Comment by niklub** [comment]
@tambulkar it is already implemented as `llm_params` parameter in [GuidanceRuntime](https://humansignal.github.io/Adala/runtimes/#adala.runtimes._guidance.GuidanceRuntime)

```
GuidanceRuntime(...llm_params={'api_base': 'your-endpoint'})
```

 You can specify any parameters from guidance framework in this dict.
Let me know if that solves your case, then I'll close the issue. Thanks

**Comment by tambulkar** [comment]
Thanks this solves the issue!
