### ISSUE TITLE
Support timeout and retry

### ISSUE THREAD

**Issue by yinggoga** [HumanSignal/Adala#41]
openai always timeout or raise exception, is there a plan to support openai request timeout and retry?

**Comment by niklub** [comment]
Hi, @yinggoga ! Thanks for your report.
Could you please provide me with your setup? That would be helpful to understand and catch the errors in a specific Runtime you use.
Meanwhile - adding support for `OpenAIChatRuntime` in this PR https://github.com/HumanSignal/Adala/pull/44

**Comment by niklub** [comment]
Ok, I see. Have you tried to run the same thing on the latest release `pip install adala==0.0.4` ?

**Comment by yinggoga** [comment]
> Ok, I see. Have you tried to run the same thing on the latest release `pip install adala==0.0.4` ?

Sure，I'm going to try it out in the next few days

**Comment by yinggoga** [comment]
> Ok, I see. Have you tried to run the same thing on the latest release `pip install adala==0.0.4` ?

It worked!Thanks~
