### ISSUE TITLE
TypeError: OpenAIChatRuntime.record_to_record() got an unexpected keyword argument 'instructions_first'

### ISSUE THREAD

**Issue by tianchiguaixia** [HumanSignal/Adala#45]
Error in executing your sample code

**Comment by tianchiguaixia** [comment]
I solved it.Network issues. Solution: 1. Download the adala file 2. Install the local: **pip install .**

**Comment by niklub** [comment]
Thanks for reporting this. Have you tried the latest release `pip install adala==0.0.4`? does it reproduce the error as well?
