### ISSUE TITLE
Update openai depedencies

### ISSUE THREAD

**Issue by goodmike31** [HumanSignal/Adala#52]
Currently, Adala requires openai==0.28.1
The latest  version available is 1.9.0.
Is there a plan to update openai depedencies?

Adala's and latest's openai libs version are not compatible e.g. below error occurs:
_"AttributeError: module 'openai' has no attribute 'api_base'. Did you mean: 'api_type'?"_

**Comment by niklub** [comment]
@goodmike31 thanks for raising this. Indeed, there is a plan to update it to the recent version, but we have to fix other dependencies, mainly `guidance` that relies on the previous version. Hope to get it updated soon - I will link the PR as soon as it's ready.

**Comment by chemeris** [comment]
Hi, @niklub do you have any timeline for the `guidance` update? It seems there are a few significant developments going on there, including the use of a lot more models.

**Comment by hawktang** [comment]
Same here for openai old version, is there any harm to use without guidance like 

```python
    runtimes = {
        'openai-gpt4':OpenAIChatRuntime(model='gpt-4-0125-preview'),
        # 'openai-gpt3': GuidanceRuntime(),
    },
    default_runtime='openai-gpt4',
    
    teacher_runtimes = {
      # 'openai-gpt3': OpenAIChatRuntime(model='gpt-3.5-turbo'),
      'openai-gpt4': OpenAIChatRuntime(model='gpt-4-0125-preview'),
    },
    
    # NOTE! If you don't have an access to gpt4 - replace it with "openai-gpt3"
    default_teacher_runtime='openai-gpt4'

**Comment by matt-bernstein** [comment]
Addressed in https://github.com/HumanSignal/Adala/pull/78
